-- ============================================================
-- SUMBER AQUARIUM PGK
-- DATABASE SCHEMA
-- PostgreSQL
-- ============================================================


-- ============================================================
-- RESET TABLES
-- ============================================================

DROP TABLE IF EXISTS riwayat_penjualan CASCADE;
DROP TABLE IF EXISTS riwayat_kematian CASCADE;
DROP TABLE IF EXISTS ikan CASCADE;


-- ============================================================
-- TABLE: ikan
-- ============================================================

CREATE TABLE ikan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    nama VARCHAR(100) NOT NULL,

    foto TEXT NOT NULL,

    kategori VARCHAR(100) NOT NULL,

    jumlah INTEGER NOT NULL DEFAULT 0
        CHECK (jumlah >= 0),

    harga NUMERIC(15, 2) NOT NULL DEFAULT 0
        CHECK (harga >= 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ============================================================
-- TABLE: riwayat_kematian
-- ============================================================

CREATE TABLE riwayat_kematian (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ikan_id BIGINT NOT NULL,

    jumlah INTEGER NOT NULL
        CHECK (jumlah > 0),

    keterangan TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_kematian_ikan
        FOREIGN KEY (ikan_id)
        REFERENCES ikan(id)
        ON DELETE RESTRICT
);


-- ============================================================
-- TABLE: riwayat_penjualan
-- ============================================================

CREATE TABLE riwayat_penjualan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    ikan_id BIGINT NOT NULL,

    jumlah INTEGER NOT NULL
        CHECK (jumlah > 0),

    harga_satuan NUMERIC(15, 2) NOT NULL
        CHECK (harga_satuan >= 0),

    total_harga NUMERIC(15, 2) NOT NULL
        CHECK (total_harga >= 0),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_penjualan_ikan
        FOREIGN KEY (ikan_id)
        REFERENCES ikan(id)
        ON DELETE RESTRICT
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_kematian_ikan_id
    ON riwayat_kematian (ikan_id);

CREATE INDEX idx_kematian_created_at
    ON riwayat_kematian (created_at);

CREATE INDEX idx_penjualan_ikan_id
    ON riwayat_penjualan (ikan_id);

CREATE INDEX idx_penjualan_created_at
    ON riwayat_penjualan (created_at);


-- ============================================================
-- AUTO UPDATE TIMESTAMP
-- ============================================================

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


CREATE TRIGGER trigger_ikan_updated_at
BEFORE UPDATE ON ikan
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();
